<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_stairs_rc-image-tile-33</name>
   <tag></tag>
   <elementGuidId>104ed33c-8db6-4271-bd26-74421a94714f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.rc-image-tile-33</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-33</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06ANYolqsya0cy0VIldr6jwxegFOeveA5nbpQ73IcEGe8bs7bDPQ2WPFH9fJEOgifzzmNtGQS-owSfR0fWu-seYGPsjx_wxlnM65VnqRAJL9zcjZF7U6P46x_KLUhJB4ey0kxohxjP6f900f2naC_mVD-LnvSCc2FGhtLjf1W8zyrIHe7kx6zo4CnAmKLGyJ4PmPahJLqbMGAL&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-33&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-33&quot;]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Katalon TestOps/iframe_html1body1div6div4iframe1_c-b0nwwhul5x3s</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td/div/div/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06ANYolqsya0cy0VIldr6jwxegFOeveA5nbpQ73IcEGe8bs7bDPQ2WPFH9fJEOgifzzmNtGQS-owSfR0fWu-seYGPsjx_wxlnM65VnqRAJL9zcjZF7U6P46x_KLUhJB4ey0kxohxjP6f900f2naC_mVD-LnvSCc2FGhtLjf1W8zyrIHe7kx6zo4CnAmKLGyJ4PmPahJLqbMGAL&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06ANYolqsya0cy0VIldr6jwxegFOeveA5nbpQ73IcEGe8bs7bDPQ2WPFH9fJEOgifzzmNtGQS-owSfR0fWu-seYGPsjx_wxlnM65VnqRAJL9zcjZF7U6P46x_KLUhJB4ey0kxohxjP6f900f2naC_mVD-LnvSCc2FGhtLjf1W8zyrIHe7kx6zo4CnAmKLGyJ4PmPahJLqbMGAL&amp;k=6Lc_Gt4ZAAAAAOm9_29UIGEij29l1W7MMGxvSOSU']</value>
   </webElementXpaths>
</WebElementEntity>
